[build]
  command = "npm run build"
  publish = "dist"
  cache = true

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=8192"
  NODE_VERSION = "18"

[build.resources]
  cpu = 2
  memory = 3072
